comfyui:
  base_url: ''
  models_path: ''
  central_cache_path: central/model_cache/comfyui
  checkpoint_urls:
  - https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/resolve/main/sd_xl_base_1.0.safetensors
