machines:
  - machine_id: "macbook"
    label: "Macbook Pro (M4, 128GB)"
    agent_base_url: "http://127.0.0.1:9001"
    notes: "For local dev, set agent_base_url to http://127.0.0.1:9001"
#  - machine_id: "gb10"
#    label: "Dell ProMax (GB10, 128GB)"
#    agent_base_url: "http://192.168.11.23:9001"
#    notes: "For local dev, set agent_base_url to http://127.0.0.1:9001"
#  - machine_id: "alienware"
#    label: "Alienware Area 51 (RTX5090, 32GB)"
#    agent_base_url: "http://192.168.11.21:9001"
#    notes: "For local dev, set agent_base_url to http://127.0.0.1:9001"
