# Updated 2026-01-30T22:22:51.538332+00:00
required:
  llm:
  - llama3.1:8b-instruct-q8_0
  - llama3.1:70b-instruct-q4_K_M
optional:
  whisper:
  - large-v3
optional_profiles:
  sdxl:
  - sdxl_1024_30steps
